# Generated by Django 6.0.3 on 2026-03-26 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('payment_methods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data Fattura')),
                ('number', models.CharField(max_length=25, verbose_name='Numero Fattura')),
                ('description', models.CharField(max_length=200, verbose_name='Descrizione')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importo')),
                ('direction', models.CharField(choices=[('purchase', 'Acquisto'), ('sale', 'Vendita')], max_length=8, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='companies.company', verbose_name='Società')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='payment_methods.paymentmethod', verbose_name='Metodo di Pagamento')),
            ],
            options={
                'verbose_name': 'Fattura',
                'verbose_name_plural': 'Fatture',
                'ordering': ['-date', 'number'],
            },
        ),
    ]
