# Generated by Django 6.0.3 on 2026-03-23 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Data Emissione')),
                ('expiration_date', models.DateField(verbose_name='Data Scadenza')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='athletes.athlete', verbose_name='Atleta')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='doctors.sportdoctor', verbose_name='Medico Sportivo')),
            ],
            options={
                'verbose_name': 'Certificazione Medico-Sportiva',
                'verbose_name_plural': 'Certificazioni Medico-Sportive',
                'ordering': ['-expiration_date', 'athlete'],
            },
        ),
    ]
