# Generated by Django 6.0.3 on 2026-03-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150, verbose_name='Ragione Sociale')),
                ('vat_number', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Partita IVA')),
                ('fiscal_code', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Codice Fiscale')),
                ('vat_equals_fc', models.BooleanField(default=False, verbose_name='P.IVA coincide con CF')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Società',
                'verbose_name_plural': 'Società',
                'ordering': ['business_name'],
            },
        ),
    ]
