# Generated by Django 6.0.3 on 2026-03-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('fiscal_code', models.CharField(max_length=16, unique=True, verbose_name='Codice Fiscale')),
                ('date_of_birth', models.DateField(verbose_name='Data di Nascita')),
                ('place_of_birth', models.CharField(max_length=150, verbose_name='Luogo di Nascita')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atleti',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Codice')),
                ('description', models.CharField(max_length=100, verbose_name='Descrizione')),
                ('age_range', models.CharField(blank=True, default='', max_length=20, verbose_name="Fascia di Eta'")),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['code'],
            },
        ),
    ]
