# Generated by Django 6.0.3 on 2026-03-21 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Codice')),
                ('description', models.CharField(max_length=100, verbose_name='Descrizione')),
                ('age_range', models.CharField(blank=True, default='', max_length=20, verbose_name="Fascia di Eta'")),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('fiscal_code', models.CharField(max_length=16, unique=True, verbose_name='Codice Fiscale')),
                ('date_of_birth', models.DateField(verbose_name='Data di Nascita')),
                ('place_of_birth', models.CharField(max_length=150, verbose_name='Luogo di Nascita')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='athletes.category', verbose_name='Categoria')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to=settings.AUTH_USER_MODEL, verbose_name='Responsabile')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='staff.trainer', verbose_name='Allenatore')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atleti',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
