# Generated by Django 6.0.3 on 2026-03-21 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to=settings.AUTH_USER_MODEL, verbose_name='Responsabile'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='staff.trainer', verbose_name='Allenatore'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='athletes.category', verbose_name='Categoria'),
        ),
    ]
