# Generated by Django 6.0.3 on 2026-03-23 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='geography.country', verbose_name='Nazionalità'),
        ),
    ]
